### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by bunnysworld** [transceptor-technology/pyleri#14]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\python37\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 208, in balloon_tip
    WindowsBalloonTip(**kwargs)
  File "C:\python37\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 141, in __init__
    self.notify(title, message, app_name)
  File "C:\python37\lib\site-packages\plyer\platforms\win\libs\balloontip.py", line 190, in notify
    raise Exception('Shell_NotifyIconW failed.')
Exception: Shell_NotifyIconW failed.

**Comment by joente** [comment]
@bunnysworld, I think this error is in package `plyer` , not `pyleri`

**Comment by bunnysworld** [comment]
i reinstalled the package after that facing the same issue

**Comment by joente** [comment]
Closing this issue as it is not related to pyleri
